"use client";
import { Inter } from "next/font/google";
import "../globals.css";
import Sidenav from "../components/dashboard/Sidenav";
import Header from "../components/dashboard/Header";
import Modal from "../components/dashboard/Modal";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Dashboard",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isOpen, setIsOpen] = React.useState(false);

  // useEffect(() => {
  //   console.log("Component mounted");
  // }, []); // Dependency array is empty

  const openModal = () => {
    //console.log("Open modal function called");
    document.body.style.overflow = "hidden";
    setIsOpen(true);
  };

  const closeModal = () => {
    //console.log("Close modal function called");
    document.body.style.overflow = "auto";
    setIsOpen(false);
  };

  const CloseDetails = () => {
    setDetails(false);
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        {isOpen && (
          <Modal isOpen={isOpen} onClose={closeModal}>
            {/* <ModalIntro closeModal={closeModal} /> */}
            {/* <Form closeModal={closeModal} /> */}
          </Modal>
        )}
        <Header />
        <div className="pt-10 flex">
          <Sidenav />
          <div className="p-6 ml-64 w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
